#!/bin/bash

set -e

# 1. Install dependencies via Conan
conan profile detect || true

conan install . --output-folder=build --build=missing \
    -s compiler.libcxx=libstdc++11 \
    -c tools.system.package_manager:mode=install \
    -c tools.system.package_manager:sudo=True

# 2. Configure CMake using the toolchain generated by Conan
# The path to the toolchain file is now correct for a single-config generator like Makefiles
cmake -S . -B build \
    -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
    -DCMAKE_BUILD_TYPE=Release

# 3. Build the project
cmake --build build --config Release --target rtype_client rtype_server

# 4. Move the executables to the project root directory
cp build/Src/Client/rtype_client .
cp build/Src/Server/rtype_server .