#!/bin/bash

set -e

# 1. Install dependencies via Conan
conan profile detect || true

conan install . --build=missing

# 2. Configure CMake using the toolchain generated by Conan
cmake -S . -B build \
    -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake \
    -DCMAKE_BUILD_TYPE=Release

# 3. Build the project
cmake --build build --config Release